<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite errors="1" failures="0" tests="2" skipped="0" name=".Users.anjsharm5.Documents.demo_app.integration_test.test" timestamp="2022-04-14T07:54:41">
    <properties>
      <property name="platform" value="vm"/>
    </properties>
    <testcase classname=".Users.anjsharm5.Documents.demo_app.integration_test.test" name="Passed test cases" time="1.012"/>
    <testcase classname=".Users.anjsharm5.Documents.demo_app.integration_test.test" name="Failure test cases" time="0.444">
      <error message="1 error, see stacktrace for details">Error:

Test failed. See exception logs above.
The test description was: Failure test cases</error>
      <system-out>══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: no matching nodes in the widget tree
  Actual: _WidgetIconFinder:&lt;exactly one widget with icon "IconData(U+0E047)" (ignoring offstage
widgets): Icon(IconData(U+0E047), dependencies: [IconTheme, Directionality])>
   Which: means one was found but none were expected

When the exception was thrown, this was the stack:
#4      main.&lt;anonymous closure> (file:///Users/anjsharm5/Documents/demo_app/integration_test/test.dart:28:9)
&lt;asynchronous suspension>
&lt;asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/anjsharm5/Documents/demo_app/integration_test/test.dart line 28
The test description was:
  Failure test cases
════════════════════════════════════════════════════════════════════════════════════════════════════</system-out>
    </testcase>
  </testsuite>
</testsuites>